### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by supertassu** [Sertex-Team/SertexOS-2#11]
Crashed with reason:
SertexOS:591:attempt to index ? (a nil value)
in account setup.

**Comment by Luca0208** [comment]
Let me take a quick look

**Comment by Luca0208** [comment]
Do you have the default language, or did you change it?

**Comment by Luca0208** [comment]
The best thing would be if you could give us the steps to re-produce the error

**Comment by Luca0208** [comment]
Ok re-produced the error, thanks for reporting. I will fix it :D

**Comment by Luca0208** [comment]
Fixed

**Comment by supertassu** [comment]
Thanks
