### ISSUE TITLE
I am "unknown"

### ISSUE THREAD

**Issue by Luca0208** [Sertex-Team/SertexOS-2#14]
If I register, it asks me "You entered Unknown as your username is that correct?"
I entered Luca, not unknown.
If I login after that it says "Welcome Unknown"
Steps to reproduce:
1.Register

**Comment by MultHub** [comment]
how to fix:
1. use the old language system
the "new" one uses variables

**Comment by MultHub** [comment]
AND the new lang files are actually lua programs

**Comment by Luca0208** [comment]
Just fix it

**Comment by Luca0208** [comment]
ok it is not fixable

**Comment by Luca0208** [comment]
You would need to rewrite the language system
I will do my own OS soon

**Comment by supertassu** [comment]
I have the same bug

**Comment by MultHub** [comment]
i think i could explain why the "new" system is sh*t

SertexOS loads the lang file
-> runs the lua code
-> no "user" at boot => Unknown

old language system:
SertexOS loads the lang file
-> reads each line
for welcome message: :format(user)

**Comment by Luca0208** [comment]
you don't even need to
Just make the user register change %user%
