### ISSUE TITLE
Links problem

### ISSUE THREAD

**Issue by Luca0208** [Sertex-Team/SertexOS-2#15]
If i try to add a link i have to keep the mouse button down at the "+" sign, also i can create Links to not existent files.

**Comment by Luca0208** [comment]
@Luca0208 Also i can't remove the Links

**Comment by LewisTehMinerz** [comment]
In what part of the code do you think is causing this?

**Comment by Luca0208** [comment]
in the code of the link program xD

Seriously, idk. I just know that it is not working i looked thru the code, but idk why

**Comment by LewisTehMinerz** [comment]
Will be started soon.

**Comment by Luca0208** [comment]
@LewisTehMinerz Ok

**Comment by LewisTehMinerz** [comment]
What error does Links throw and what line?

**Comment by Luca0208** [comment]
@LewisTehMinerz As I explained it is not erroring, it has just bugged behaviour

**Comment by Ale32bit** [comment]
I'll fix it

**Comment by Luca0208** [comment]
So will this be fixed or not?
