### ISSUE TITLE
Firewolf Overritten Itself...?

### ISSUE THREAD

**Issue by LewisTehMinerz** [Sertex-Team/SertexOS-2#3]
So, Firewolf crashed, then doesn't start. Checked the file contents:

```
9001
```

THE HELL?

**Comment by Ale2610** [comment]
ask to gravityscore

**Comment by LewisTehMinerz** [comment]
Lel, GravityScore is going to have a treat xD

**Comment by Ale32bit** [comment]
Really?

**Comment by LewisTehMinerz** [comment]
waffle.io is not good sometimes :P
