### ISSUE TITLE
French traduction Add

### ISSUE THREAD

**Issue by r00tKiller** [Sertex-Team/SertexOS-2#8]
settings_dynamicClock = "Dynamic Clock"

dynamicClock_enable = "Enable Dynamic clock? (It may lags)"

================

settings_dynamicClock = "Horloge dynamique"

dynamicClock_enable = "Activer l'horloge dynamique? (Peut causer des lags)"

**Comment by Luca0208** [comment]
"Merged", next time please pull request, we can merge it better
